import { type NextPage } from "next";
import Head from "next/head";
import { PageLayout } from "~/components/layout";

const Post: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>Post Page</PageLayout>
    </>
  );
};

export default Post;
